codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 100%
        threshold: 0%
        # advanced
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
    patch:
      default:
        # basic
        target: 100%
        threshold: 0%
        # advanced
        if_no_uploads: error
  
  # Enable carryforward of coverage for files not included in the current report
  flag_management:
    default_rules:
      carryforward: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
