version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-starter-app
    restart: always
    ports:
      - '${PORT:-3001}:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - nestjs-network

  postgres:
    image: postgres:17-alpine
    container_name: nestjs-starter-postgres
    restart: always
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nestjs}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nestjs-network

  redis:
    image: redis:7-alpine
    container_name: nestjs-starter-redis
    restart: always
    ports:
      - '${REDIS_PORT:-6380}:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
